require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MasteriesController do

  # This should return the minimal set of attributes required to create a valid
  # Mastery. As you add validations to Mastery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MasteriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all masteries as @masteries" do
      mastery = Mastery.create! valid_attributes
      get :index, {}, valid_session
      assigns(:masteries).should eq([mastery])
    end
  end

  describe "GET show" do
    it "assigns the requested mastery as @mastery" do
      mastery = Mastery.create! valid_attributes
      get :show, {:id => mastery.to_param}, valid_session
      assigns(:mastery).should eq(mastery)
    end
  end

  describe "GET new" do
    it "assigns a new mastery as @mastery" do
      get :new, {}, valid_session
      assigns(:mastery).should be_a_new(Mastery)
    end
  end

  describe "GET edit" do
    it "assigns the requested mastery as @mastery" do
      mastery = Mastery.create! valid_attributes
      get :edit, {:id => mastery.to_param}, valid_session
      assigns(:mastery).should eq(mastery)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Mastery" do
        expect {
          post :create, {:mastery => valid_attributes}, valid_session
        }.to change(Mastery, :count).by(1)
      end

      it "assigns a newly created mastery as @mastery" do
        post :create, {:mastery => valid_attributes}, valid_session
        assigns(:mastery).should be_a(Mastery)
        assigns(:mastery).should be_persisted
      end

      it "redirects to the created mastery" do
        post :create, {:mastery => valid_attributes}, valid_session
        response.should redirect_to(Mastery.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved mastery as @mastery" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mastery.any_instance.stub(:save).and_return(false)
        post :create, {:mastery => { "name" => "invalid value" }}, valid_session
        assigns(:mastery).should be_a_new(Mastery)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Mastery.any_instance.stub(:save).and_return(false)
        post :create, {:mastery => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested mastery" do
        mastery = Mastery.create! valid_attributes
        # Assuming there are no other masteries in the database, this
        # specifies that the Mastery created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Mastery.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => mastery.to_param, :mastery => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested mastery as @mastery" do
        mastery = Mastery.create! valid_attributes
        put :update, {:id => mastery.to_param, :mastery => valid_attributes}, valid_session
        assigns(:mastery).should eq(mastery)
      end

      it "redirects to the mastery" do
        mastery = Mastery.create! valid_attributes
        put :update, {:id => mastery.to_param, :mastery => valid_attributes}, valid_session
        response.should redirect_to(mastery)
      end
    end

    describe "with invalid params" do
      it "assigns the mastery as @mastery" do
        mastery = Mastery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mastery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mastery.to_param, :mastery => { "name" => "invalid value" }}, valid_session
        assigns(:mastery).should eq(mastery)
      end

      it "re-renders the 'edit' template" do
        mastery = Mastery.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Mastery.any_instance.stub(:save).and_return(false)
        put :update, {:id => mastery.to_param, :mastery => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested mastery" do
      mastery = Mastery.create! valid_attributes
      expect {
        delete :destroy, {:id => mastery.to_param}, valid_session
      }.to change(Mastery, :count).by(-1)
    end

    it "redirects to the masteries list" do
      mastery = Mastery.create! valid_attributes
      delete :destroy, {:id => mastery.to_param}, valid_session
      response.should redirect_to(masteries_url)
    end
  end

end
